version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:lts
    working_directory: ~/repo/task-tracker

jobs:
  run-tests-and-build:
    executor: default
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Trigger EAS build
          command: npx eas-cli build --platform android --profile preview  --non-interactive --no-wait

workflows:
  build-app:
    jobs:
      - run-tests-and-build
